"""Add is_deleted field to knowledge_documents table

Revision ID: 74584b01099b
Revises: d35049d6b383
Create Date: 2025-08-04 18:43:19.696700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74584b01099b'
down_revision = 'd35049d6b383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        # Add is_deleted column with nullable=True and default=False
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Update all existing records to set is_deleted=False
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE knowledge_documents SET is_deleted = FALSE WHERE is_deleted IS NULL"))

    # Now alter the column to be NOT NULL
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.alter_column('is_deleted', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
